name: Buf Linting

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
    paths:
      - src/main/proto/**

jobs:
  validate-protos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: bufbuild/buf-setup-action@a47c93e0b1648d5651a065437926377d060baa99 # v1.50.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate protocol buffers linting
        uses: bufbuild/buf-lint-action@06f9dd823d873146471cfaaf108a993fe00e5325 # v1.1.1
        with:
          input: src/main/proto

      - name: Validate protocol buffers formatting
        run: buf format src/main/proto --diff --exit-code

      - name: Validate protocol buffers breaking changes
        uses: bufbuild/buf-breaking-action@c57b3d842a5c3f3b454756ef65305a50a587c5ba
        with:
          input: src/main/proto
          against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=master,ref=${GITHUB_BASE_REF},subdir=src/main/proto"
